version: '3'
services:
  graphdb:
    image: neo4j:latest
    ports:
      - '7474:7474'
      - '7687:7687'
    volumes:
      - $HOME/neo4j/data:/neo4j/data
      - $HOME/neo4j/logs:/neo4j/logs
    environment:
      - NEO4J_AUTH=neo4j/password

  frontend:
    image: node:latest
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: bash -c "npm install && npm start"
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

  backend:
    build: ./backend
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - '5000:5000'
    environment:
      - FLASK_ENV=development
